#tabuada
n = int(input("Digite um numero para ver a sua tabuada: "))
print("--------------------Multiplicação--------------------")
print("{}*{} = {}".format(n, 1, n*1))
print("{}*{} = {}".format(n, 2, n*2))
print("{}*{} = {}".format(n, 3, n*3))
print("{}*{} = {}".format(n, 4, n*4))
print("{}*{} = {}".format(n, 5, n*5))
print("{}*{} = {}".format(n, 6, n*6))
print("{}*{} = {}".format(n, 7, n*7))
print("{}*{} = {}".format(n, 8, n*8))
print("{}*{} = {}".format(n, 9, n*9))
print("{}*{} = {}".format(n, 10, n*10))

print("--------------------Soma--------------------")

print("{}+{} = {}".format(n, 1, n+1))
print("{}+{} = {}".format(n, 2, n+2))
print("{}+{} = {}".format(n, 3, n+3))
print("{}+{} = {}".format(n, 4, n+4))
print("{}+{} = {}".format(n, 5, n+5))
print("{}+{} = {}".format(n, 6, n+6))
print("{}+{} = {}".format(n, 7, n+7))
print("{}+{} = {}".format(n, 8, n+8))
print("{}+{} = {}".format(n, 9, n+9))
print("{}+{} = {}".format(n, 10, n+10))

print("--------------------Divisão--------------------")

print("{}/{} = {}".format(n, 1, n/1))
print("{}/{} = {}".format(n, 2, n/2))
print("{}/{} = {:.2f}".format(n, 3, n/3))
print("{}/{} = {}".format(n, 4, n/4))
print("{}/{} = {}".format(n, 5, n/5))
print("{}/{} = {:.2f}".format(n, 6, n/6))
print("{}/{} = {:.2f}".format(n, 7, n/7))
print("{}/{} = {}".format(n, 8, n/8))
print("{}/{} = {:.2f}".format(n, 9, n/9))
print("{}/{} = {}".format(n, 10, n/10))

print("--------------------Subtração--------------------")

print("{}-{} = {}".format(n, 1, n-1))
print("{}-{} = {}".format(n, 2, n-2))
print("{}-{} = {}".format(n, 3, n-3))
print("{}-{} = {}".format(n, 4, n-4))
print("{}-{} = {}".format(n, 5, n-5))
print("{}-{} = {}".format(n, 6, n-6))
print("{}-{} = {}".format(n, 7, n-7))
print("{}-{} = {}".format(n, 8, n-8))
print("{}-{} = {}".format(n, 9, n-9))
print("{}-{} = {}".format(n, 10, n-10))